import { UploaderLabels, UploaderTheme } from './types.js';

export const DEFAULT_LABELS: UploaderLabels = {
    title: 'Upload Files',
    dropzonePrompt: 'Drag and drop files here, or',
    dropzoneSubtext: 'Support for chunked, resumable, and high-speed multi-file transfers',
    browseButton: 'Browse Files',
    uploadButton: 'Start Upload',
    pauseButton: 'Pause',
    resumeButton: 'Resume',
    cancelButton: 'Cancel',
    removeButton: 'Remove',
    retryButton: 'Retry',
    clearCompletedButton: 'Clear Completed',
    closeModalButton: 'Close',
    statusQueued: 'Queued',
    statusUploading: 'Uploading',
    statusPaused: 'Paused',
    statusCompleted: 'Completed',
    statusError: 'Failed',
    statusCanceled: 'Canceled',
    speedLabel: 'Speed',
    etaLabel: 'ETA',
    totalProgressLabel: 'Overall Progress',
    maxFilesError: 'Maximum number of allowed files exceeded.',
    maxSizeError: 'File exceeds maximum allowed size.',
    typeError: 'File type is not permitted.',
    emptyQueueMessage: 'No files in upload queue.',
};

export const THEME_PRESETS: Record<UploaderTheme, Record<string, string>> = {
    light: {
        '--jengo-primary': '#2563eb',
        '--jengo-primary-hover': '#1d4ed8',
        '--jengo-primary-active': '#1e40af',
        '--jengo-primary-text': '#ffffff',
        '--jengo-bg': '#ffffff',
        '--jengo-surface': '#f8fafc',
        '--jengo-surface-hover': '#f1f5f9',
        '--jengo-text': '#0f172a',
        '--jengo-text-muted': '#64748b',
        '--jengo-border': '#e2e8f0',
        '--jengo-border-focus': '#3b82f6',
        '--jengo-border-dashed': '#cbd5e1',
        '--jengo-success': '#10b981',
        '--jengo-warning': '#f59e0b',
        '--jengo-error': '#ef4444',
        '--jengo-radius': '0.625rem',
        '--jengo-radius-sm': '0.375rem',
        '--jengo-shadow': '0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)',
        '--jengo-shadow-modal': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        '--jengo-backdrop': 'rgba(15, 23, 42, 0.5)',
        '--jengo-font': 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    dark: {
        '--jengo-primary': '#3b82f6',
        '--jengo-primary-hover': '#60a5fa',
        '--jengo-primary-active': '#2563eb',
        '--jengo-primary-text': '#ffffff',
        '--jengo-bg': '#0f172a',
        '--jengo-surface': '#1e293b',
        '--jengo-surface-hover': '#334155',
        '--jengo-text': '#f8fafc',
        '--jengo-text-muted': '#94a3b8',
        '--jengo-border': '#334155',
        '--jengo-border-focus': '#60a5fa',
        '--jengo-border-dashed': '#475569',
        '--jengo-success': '#34d399',
        '--jengo-warning': '#fbbf24',
        '--jengo-error': '#f87171',
        '--jengo-radius': '0.625rem',
        '--jengo-radius-sm': '0.375rem',
        '--jengo-shadow': '0 10px 15px -3px rgba(0, 0, 0, 0.3)',
        '--jengo-shadow-modal': '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
        '--jengo-backdrop': 'rgba(0, 0, 0, 0.75)',
        '--jengo-font': 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    minimal: {
        '--jengo-primary': '#18181b',
        '--jengo-primary-hover': '#27272a',
        '--jengo-primary-active': '#09090b',
        '--jengo-primary-text': '#ffffff',
        '--jengo-bg': '#ffffff',
        '--jengo-surface': '#fafafa',
        '--jengo-surface-hover': '#f4f4f5',
        '--jengo-text': '#18181b',
        '--jengo-text-muted': '#71717a',
        '--jengo-border': '#e4e4e7',
        '--jengo-border-focus': '#18181b',
        '--jengo-border-dashed': '#d4d4d8',
        '--jengo-success': '#16a34a',
        '--jengo-warning': '#d97706',
        '--jengo-error': '#dc2626',
        '--jengo-radius': '0.25rem',
        '--jengo-radius-sm': '0.125rem',
        '--jengo-shadow': 'none',
        '--jengo-shadow-modal': '0 4px 12px rgba(0, 0, 0, 0.08)',
        '--jengo-backdrop': 'rgba(0, 0, 0, 0.4)',
        '--jengo-font': 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    corporate: {
        '--jengo-primary': '#0f766e',
        '--jengo-primary-hover': '#115e59',
        '--jengo-primary-active': '#134e4a',
        '--jengo-primary-text': '#ffffff',
        '--jengo-bg': '#ffffff',
        '--jengo-surface': '#f0fdfa',
        '--jengo-surface-hover': '#ccfbf1',
        '--jengo-text': '#134e4a',
        '--jengo-text-muted': '#0d9488',
        '--jengo-border': '#99f6e4',
        '--jengo-border-focus': '#0f766e',
        '--jengo-border-dashed': '#5eead4',
        '--jengo-success': '#059669',
        '--jengo-warning': '#d97706',
        '--jengo-error': '#e11d48',
        '--jengo-radius': '0.5rem',
        '--jengo-radius-sm': '0.25rem',
        '--jengo-shadow': '0 4px 6px -1px rgba(15, 118, 110, 0.1)',
        '--jengo-shadow-modal': '0 20px 25px -5px rgba(15, 118, 110, 0.2)',
        '--jengo-backdrop': 'rgba(19, 78, 74, 0.6)',
        '--jengo-font': 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    glass: {
        '--jengo-primary': '#6366f1',
        '--jengo-primary-hover': '#4f46e5',
        '--jengo-primary-active': '#4338ca',
        '--jengo-primary-text': '#ffffff',
        '--jengo-bg': 'rgba(255, 255, 255, 0.75)',
        '--jengo-surface': 'rgba(241, 245, 249, 0.6)',
        '--jengo-surface-hover': 'rgba(226, 232, 240, 0.8)',
        '--jengo-text': '#0f172a',
        '--jengo-text-muted': '#475569',
        '--jengo-border': 'rgba(255, 255, 255, 0.5)',
        '--jengo-border-focus': '#6366f1',
        '--jengo-border-dashed': 'rgba(99, 102, 241, 0.4)',
        '--jengo-success': '#10b981',
        '--jengo-warning': '#f59e0b',
        '--jengo-error': '#ef4444',
        '--jengo-radius': '1rem',
        '--jengo-radius-sm': '0.5rem',
        '--jengo-shadow': '0 8px 32px 0 rgba(31, 38, 135, 0.12)',
        '--jengo-shadow-modal': '0 8px 32px 0 rgba(31, 38, 135, 0.3)',
        '--jengo-backdrop': 'rgba(15, 23, 42, 0.4)',
        '--jengo-font': 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    custom: {
        '--jengo-primary': '#2563eb',
        '--jengo-primary-hover': '#1d4ed8',
        '--jengo-primary-active': '#1e40af',
        '--jengo-primary-text': '#ffffff',
        '--jengo-bg': '#ffffff',
        '--jengo-surface': '#f8fafc',
        '--jengo-surface-hover': '#f1f5f9',
        '--jengo-text': '#0f172a',
        '--jengo-text-muted': '#64748b',
        '--jengo-border': '#e2e8f0',
        '--jengo-border-focus': '#3b82f6',
        '--jengo-border-dashed': '#cbd5e1',
        '--jengo-success': '#10b981',
        '--jengo-warning': '#f59e0b',
        '--jengo-error': '#ef4444',
        '--jengo-radius': '0.5rem',
        '--jengo-radius-sm': '0.25rem',
        '--jengo-shadow': 'none',
        '--jengo-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.15)',
        '--jengo-backdrop': 'rgba(0, 0, 0, 0.5)',
        '--jengo-font': 'inherit',
    },
};

export function resolveThemeVariables(
    theme: UploaderTheme = 'light',
    customVariables?: Record<string, string>
): Record<string, string> {
    const preset = THEME_PRESETS[theme] ?? THEME_PRESETS.light;
    const resolved = { ...preset };

    if (customVariables) {
        for (const [k, v] of Object.entries(customVariables)) {
            const cssVar = k.startsWith('--') ? k : `--jengo-${k}`;
            resolved[cssVar] = v;
        }
    }

    return resolved;
}
